# Generated by Django 3.2.13 on 2022-07-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrow_date',
            field=models.DateField(blank=True, help_text='borrowed book?', null=True),
        ),
    ]
