# Generated by Django 3.2.13 on 2022-07-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0004_alter_borrower_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={},
        ),
    ]
