# Generated by Django 3.2.13 on 2022-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0005_alter_borrower_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
