# Generated by Django 3.2.13 on 2022-07-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0006_alter_borrower_borrow_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ['borrow_date']},
        ),
    ]
