# Generated by Django 3.2.13 on 2022-07-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0007_alter_borrower_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=False, help_text='borrowed book?'),
        ),
    ]
